version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: bubblymaps/web:latest
    container_name: bubblymaps.org
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DATABASE_URL: "postgresql://user:pass@host:port/db_name?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your_secret"
      GOOGLE_CLIENT_ID: "your_cli"
      GOOGLE_CLIENT_SECRET: "your_secret"
      RESEND_API_KEY: "your_key"
      API_TOKEN: "your_key"
      MINIO_USER: "user"
      MINIO_PASSWORD: "pass"
      MINIO_URL: "https://host.name.here"
      MINIO_BUCKET: "bucket_name"
      APP_VERSION: "v3.0.2"
